### ISSUE TITLE
Playbook creation

### ISSUE THREAD

**Issue by dmoore44** [pan-unit42/playbook_viewer#1]
This isn't really an issue so much as a question... 

I know there are tools like cti-python-stix2 or cyberstationFX (https://github.com/workingDog/cyberstationFX) that allow the creation of STIX 2.0 documents but was curious what Unit 42 used to create playbooks.

**Comment by ireo** [comment]
Sorry for the slow reply here. We don't have a public tool released for creating Playbooks yet, but intend to release on next year.

**Comment by jachockey012** [comment]
Any public tool released for creating Playbooks?

**Comment by ghost** [comment]
> Sorry for the slow reply here. We don't have a public tool released for creating Playbooks yet, but intend to release on next year.

Any public tool released for creating Playbooks?
