### ISSUE TITLE
T1060 ID is different than Mitre's T1060 ID

### ISSUE THREAD

**Issue by HamptonJ** [pan-unit42/playbook_viewer#10]
The ID of the T1060 present in MenuPass.json is `attack-pattern--d586e6f2-83a6-43f1-b267-c47ab031b33e`, but Mitre's is `attack-pattern--9422fc14-1c43-410d-ab0f-a709b76c72dc`. Would it be possible to update the id to match?

**Comment by eiyuki** [comment]
Fixed in the latest commit. Keeping all attack patterns up to date can be a challenge, as described in a bit more detail [here](https://github.com/pan-unit42/playbook_viewer/issues/4)

Please let us know if you notice any additional issues.
