### ISSUE TITLE
Leverage MITRE's STIX data?

### ISSUE THREAD

**Issue by infosec-alchemist** [pan-unit42/playbook_viewer#3]
Saw your presentation at ATTACKCon, nice job.

I was hoping to leverage your data along with the MITRE ATTACK Data (https://github.com/mitre/cti), however, the attack pattern ID's do not match, and so we would have duplicates.

Any thought of leveraging MITRE's STIX objects?

Thanks

**Comment by eiyuki** [comment]
The MITRE techniques in the Playbooks have been updated and now use MITRE's UUIDs.

Please see [Deprecated Techniques](https://github.com/pan-unit42/playbook_viewer/issues/4) for another related issue.
