### ISSUE TITLE
Playbook creation

### ISSUE THREAD

**Issue by jordisk** [pan-unit42/playbook_viewer#8]
I have added a new json file (stix2 format) to the playbooks folder and modified the html to show it, but nothing is displayed.

Does you playbook viewer support adding new playbooks or only the ones created by you?
As mentioned in your repo, you use att&ck framework and STIX 2, but exporting a MISP event maped to att&ck framework in stix 2 seems to not work at all.

Many thanks

**Comment by eiyuki** [comment]
A Playbook is a STIX 2.0 JSON file with a specific structure. I have added some documentation and examples that can be seen [here](https://github.com/pan-unit42/playbook_viewer/blob/master/docs/Playbook%20Structure.md)

MISP's exporter does not know the structure of a Playbook. While the file is valid STIX 2.0 JSON, it is not a valid Playbook.

It may be possible to map this to a Playbook. However, I took a brief look at MISP, and was not sure which options or plugins were used to export.
